package lld.wru.model;

public class Friend {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.id
     *
     * @mbg.generated Sat Nov 18 10:50:50 IRKT 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.phone_num1
     *
     * @mbg.generated Sat Nov 18 10:50:50 IRKT 2017
     */
    private String phoneNum1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.phone_num2
     *
     * @mbg.generated Sat Nov 18 10:50:50 IRKT 2017
     */
    private String phoneNum2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.id
     *
     * @return the value of friend.id
     *
     * @mbg.generated Sat Nov 18 10:50:50 IRKT 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.id
     *
     * @param id the value for friend.id
     *
     * @mbg.generated Sat Nov 18 10:50:50 IRKT 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.phone_num1
     *
     * @return the value of friend.phone_num1
     *
     * @mbg.generated Sat Nov 18 10:50:50 IRKT 2017
     */
    public String getPhoneNum1() {
        return phoneNum1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.phone_num1
     *
     * @param phoneNum1 the value for friend.phone_num1
     *
     * @mbg.generated Sat Nov 18 10:50:50 IRKT 2017
     */
    public void setPhoneNum1(String phoneNum1) {
        this.phoneNum1 = phoneNum1 == null ? null : phoneNum1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.phone_num2
     *
     * @return the value of friend.phone_num2
     *
     * @mbg.generated Sat Nov 18 10:50:50 IRKT 2017
     */
    public String getPhoneNum2() {
        return phoneNum2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.phone_num2
     *
     * @param phoneNum2 the value for friend.phone_num2
     *
     * @mbg.generated Sat Nov 18 10:50:50 IRKT 2017
     */
    public void setPhoneNum2(String phoneNum2) {
        this.phoneNum2 = phoneNum2 == null ? null : phoneNum2.trim();
    }
}