package lld.wru.model;

public class Location {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.id
     *
     * @mbg.generated Sat Nov 18 10:50:50 IRKT 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.phone_num
     *
     * @mbg.generated Sat Nov 18 10:50:50 IRKT 2017
     */
    private String phoneNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.latitude
     *
     * @mbg.generated Sat Nov 18 10:50:50 IRKT 2017
     */
    private Double latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.longitude
     *
     * @mbg.generated Sat Nov 18 10:50:50 IRKT 2017
     */
    private Double longitude;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.id
     *
     * @return the value of location.id
     *
     * @mbg.generated Sat Nov 18 10:50:50 IRKT 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.id
     *
     * @param id the value for location.id
     *
     * @mbg.generated Sat Nov 18 10:50:50 IRKT 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.phone_num
     *
     * @return the value of location.phone_num
     *
     * @mbg.generated Sat Nov 18 10:50:50 IRKT 2017
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.phone_num
     *
     * @param phoneNum the value for location.phone_num
     *
     * @mbg.generated Sat Nov 18 10:50:50 IRKT 2017
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum == null ? null : phoneNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.latitude
     *
     * @return the value of location.latitude
     *
     * @mbg.generated Sat Nov 18 10:50:50 IRKT 2017
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.latitude
     *
     * @param latitude the value for location.latitude
     *
     * @mbg.generated Sat Nov 18 10:50:50 IRKT 2017
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.longitude
     *
     * @return the value of location.longitude
     *
     * @mbg.generated Sat Nov 18 10:50:50 IRKT 2017
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.longitude
     *
     * @param longitude the value for location.longitude
     *
     * @mbg.generated Sat Nov 18 10:50:50 IRKT 2017
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }
}